### ISSUE TITLE
Installation requirements information

### ISSUE THREAD

**Issue by ClimbTheWorld** [maebli/m-bus-parser#22]
I did install the pymbusparser as follows:

`
PS> poetry add pymbusparser
Using version ^0.0.0 for pymbusparser

Updating dependencies
Resolving dependencies... (6.2s)

Package operations: 1 install, 0 updates, 0 removals

  - Installing pymbusparser (0.0.0): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel

  Running `maturin pep517 build-wheel -i C:\Users\user\AppData\Local\Temp\tmp9szeo50w\.venv\Scripts\python.exe --compatibility off`
  💥 maturin failed
    Caused by: Cargo metadata failed. Do you have cargo in your PATH?
    Caused by: program not found
  Error: command ['maturin', 'pep517', 'build-wheel', '-i', 'C:\\Users\\user\\AppData\\Local\\Temp\\tmp9szeo50w\\.venv\\Scripts\\python.exe', '--compatibility', 'off'] returned non-zero exit status 1

  at C:\tools\miniconda3\lib\site-packages\poetry\installation\chef.py:164 in _prepare
      160│
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│
      163│             if error is not None:
    → 164│                 raise error from None
      165│
      166│             return path
      167│
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with pymbusparser (0.0.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "pymbusparser (==0.0.0)"'.
`
I had to install: PS> winget install Rustlang.Rustup

**Comment by maebli** [comment]
Try again now with version v0.0.1 it has been published for 151 different targets

**Comment by maebli** [comment]
tested, a lot of targets added works
